In [4]:
import numpy as np
import pandas as pd

data = pd.read_csv("data/unimelb_training.csv", header=0, dtype="str")
data = data.drop("Unnamed: 251", axis=1)
data["Year"] = data["Start.date"].map(lambda x: float(x.split("/")[2]))
data["Year"].dtype


numerical_data_feature_category = [
    ("RFCD.Percentage.", 5), 
    ("SEO.Percentage.", 5), 
    ("Year.of.Birth.", 15),
    ("Number.of.Successful.Grant.", 15),
    ("Number.of.Unsuccessful.Grant.", 15),
    ("A..", 15),
    ("A.", 15),
    ("B.", 15),
    ("C.", 15)
]

for feature_name, feature_range in numerical_data_feature_category:
    numerical_data_features = [feature_name+str(i) for i in range(1, feature_range+1)]
    for numerical_data_feature in numerical_data_features:
        data[numerical_data_feature] = data[numerical_data_feature].astype(float)

data.dtypes

Grant.Application.ID                        object
Grant.Status                                object
Sponsor.Code                                object
Grant.Category.Code                         object
Contract.Value.Band...see.note.A            object
Start.date                                  object
RFCD.Code.1                                 object
RFCD.Percentage.1                          float64
RFCD.Code.2                                 object
RFCD.Percentage.2                          float64
RFCD.Code.3                                 object
RFCD.Percentage.3                          float64
RFCD.Code.4                                 object
RFCD.Percentage.4                          float64
RFCD.Code.5                                 object
RFCD.Percentage.5                          float64
SEO.Code.1                                  object
SEO.Percentage.1                           float64
SEO.Code.2                                  object
SEO.Percentage.2                           float64
SEO.Code.3                                  object
SEO.Percentage.3                           float64
SEO.Code.4                                  object
SEO.Percentage.4                           float64
SEO.Code.5                                  object
SEO.Percentage.5                           float64
Person.ID.1                                 object
Role.1                                      object
Year.of.Birth.1                            float64
Country.of.Birth.1                          object
                                            ...
Role.14                                     object
Year.of.Birth.14                           float64
Country.of.Birth.14                         object
Home.Language.14                            object
Dept.No..14                                 object
Faculty.No..14                              object
With.PHD.14                                 object
No..of.Years.in.Uni.at.Time.of.Grant.14     object
Number.of.Successful.Grant.14              float64
Number.of.Unsuccessful.Grant.14            float64
A..14                                      float64
A.14                                       float64
B.14                                       float64
C.14                                       float64
Person.ID.15                                object
Role.15                                     object
Year.of.Birth.15                           float64
Country.of.Birth.15                         object
Home.Language.15                            object
Dept.No..15                                 object
Faculty.No..15                              object
With.PHD.15                                 object
No..of.Years.in.Uni.at.Time.of.Grant.15     object
Number.of.Successful.Grant.15              float64
Number.of.Unsuccessful.Grant.15            float64
A..15                                      float64
A.15                                       float64
B.15                                       float64
C.15                                       float64
Year                                       float64
dtype: object

In [3]:
data.head()

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,Faculty.No..15,With.PHD.15,No..of.Years.in.Uni.at.Time.of.Grant.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15,C.15,Year
0,1,1,NaN,NaN,A,8/11/05,280199,100.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
1,2,1,2B,10A,B,11/11/05,280103,30.0,280106,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
2,3,1,29A,10B,A,14/11/05,321004,60.0,321216,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
3,4,1,40D,10B,C,15/11/05,270602,50.0,320602,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,5,0,59C,10A,A,16/11/05,260500,34.0,280000,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [5]:
def process_column(data, prefix, nb_max=15):
    unique_values = set([])
    all_values = []
    for i in range(1, nb_max+1):
        unique_values.update(data[prefix+str(i)].unique())
        all_values.extend(list(data[prefix+str(i)]))
    return unique_values, all_values

In [6]:
unique_roles, all_roles = process_column(data, "Role.")
print(list(unique_roles))
print(len(all_roles)) # 8708*15
print(sum([True if np.isreal(x) and np.isnan(x) else False for x in all_roles])/len(all_roles)) # this value is high because we concatenate all the 15 persons

pd.Series(all_roles).value_counts()

['EXT_CHIEF_INVESTIGATOR', nan, 'STUD_CHIEF_INVESTIGATOR', 'HONVISIT', 'STUDRES', 'DELEGATED_RESEARCHER', 'PRINCIPAL_SUPERVISOR', 'CHIEF_INVESTIGATOR', 'EXTERNAL_ADVISOR']
130620
0.866054203031695

CHIEF_INVESTIGATOR         12136
EXT_CHIEF_INVESTIGATOR      3732
STUD_CHIEF_INVESTIGATOR      586
PRINCIPAL_SUPERVISOR         536
DELEGATED_RESEARCHER         315
STUDRES                      157
HONVISIT                      29
EXTERNAL_ADVISOR               5
dtype: int64

In [7]:
unique_cob, all_cob = process_column(data, "Country.of.Birth.")
print(list(unique_cob))
print(sum([True if np.isreal(x) and np.isnan(x) else False for x in all_cob])/len(all_cob))

pd.Series(all_cob).value_counts()

[nan, 'The Americas', 'Middle East and Africa', 'Great Britain', 'Asia Pacific', 'New Zealand', 'Australia', 'South Africa', 'Eastern Europe', 'Western Europe', 'North America']
0.911751645996019

Australia                 8500
Great Britain             1011
Asia Pacific               549
Western Europe             500
North America              352
Eastern Europe             193
New Zealand                134
Middle East and Africa     100
South Africa                97
The Americas                91
dtype: int64

In [8]:
print(sum(data["Role.1"].isnull()))

data["Sponsor.Code"].unique()

98

array([nan, '2B', '29A', '40D', '59C', '4D', '28D', '136D', '100D', '1A',
       '21A', '24D', '148D', '12D', '62B', '138B', '60D', '143C', '90B',
       '18B', '89A', '34B', '47C', '36D', '32D', '172D', '184D', '5A',
       '63C', '74B', '6B', '170B', '166B', '101A', '33A', '164D', '75C',
       '161A', '157A', '9A', '126B', '149A', '53A', '94B', '97A', '160D',
       '51C', '167C', '135C', '65A', '42B', '87C', '169A', '95C', '103C',
       '147C', '133A', '150B', '155C', '174B', '83C', '175C', '139C',
       '202B', '13A', '168D', '113A', '134B', '20D', '141A', '80D', '91C',
       '187C', '26B', '162B', '93A', '84D', '158B', '55C', '77A', '429A',
       '140D', '23C', '142B', '112D', '111C', '154B', '185A', '151C', '3C',
       '428D', '137A', '37A', '146B', '176D', '145A', '85A', '14B', '69A',
       '41A', '427C', '49A', '7C', '44D', '163C', '144D', '177A', '39C',
       '153A', '173A', '159C', '178B', '156D', '186B', '152D', '171C',
       '201A', '182B', '183C', '52D', '132D', '219C', '227C', '56D', '73A',
       '107C', '224D', '188D', '229A', '230B', '210B', '430B', '86B',
       '179C', '234B', '198B', '305A', '199C', '200D', '191C', '238B',
       '222B', '223C', '54B', '196D', '216D', '120D', '190B', '189A',
       '214B', '215C', '237A', '233A', '38B', '82B', '66B', '194B', '225A',
       '212D', '208D', '180D', '68D', '211C', '203C', '192D', '228D',
       '205A', '213A', '130B', '48D', '206B', '207C', '72D', '27C', '251C',
       '204D', '193A', '195C', '239C', '67C', '217A', '218B', '226B',
       '431C', '232D', '197A', '165A', '247C', '220D', '221A', '245A',
       '282B', '11C', '250B', '252D', '292D', '235C', '105A', '242B',
       '240D', '243C', '15C', '244D', '246B', '278B', '241A', '270B',
       '277A', '275C', '295C', '372D', '284D', '258B', '297A', '256D',
       '255C', '289A', '286B', '280D', '253A', '276D', '128D', '433A',
       '81A', '298B', '78B', '435C', '285A', '339C', '288D', '294B',
       '325A', '300D', '287C', '296D', '266B', '265A', '268D', '302B',
       '257A', '263C', '269A', '434B', '16D', '432D', '279C', '272D',
       '274B', '271C', '267C', '262B', '373A', '259C', '260D', '261A',
       '281A', '309A', '308D', '304D', '303C', '307C', '310B', '326B',
       '316D', '273A', '436D', '314B', '346B', '324D', '318B', '313A',
       '312D', '311C', '315C', '437A', '118B', '299C', '330B', '319C',
       '328D', '331C', '334B', '317A', '323C', '347C', '415C', '58B',
       '374B', '362B', '363C', '342B', '357A', '370B', '371C', '290B',
       '349A', '10B', '329A'], dtype=object)

# Descriptive analysis

In [267]:
def process_column(data, prefix, nb_max=15):
    unique_values = set([])
    all_values = []
    for i in range(1, nb_max+1):
        unique_values.update(data[prefix+str(i)].unique())
        all_values.extend(list(data[prefix+str(i)]))
    return unique_values, all_values

## Person

In [9]:
person_features = [
    'Person.ID.', 'Role.', 'Year.of.Birth.', 'Country.of.Birth.', 'Home.Language.', 'Dept.No..', 'Faculty.No..', 
    'With.PHD.', 'No..of.Years.in.Uni.at.Time.of.Grant.', 'Number.of.Successful.Grant.', 'Number.of.Unsuccessful.Grant.',
    'A..', 'A.', 'B.', 'C.',
]

In [10]:
# Id and person
person_unique_id, person_all_id = process_column(data, 'Person.ID.')
if np.nan in person_unique_id: 
    person_unique_id.remove(np.nan)

print(len(person_unique_id))
list(person_unique_id)[:20]

2875

['79062',
 '82432',
 '1125477',
 '15987',
 '58457',
 '314962',
 '65812',
 '14187',
 '78822',
 '397557',
 '770507',
 '730127',
 '127542',
 '67367',
 '482182',
 '500467',
 '35672',
 '606707',
 '493297',
 '66877']

In [11]:
# from collections import defaultdict

# persons_dict = defaultdict(dict)
# for person_id in person_unique_id:
#     column_number = 1
#     while(column_number <= 15):
#         column_name = 'Person.ID.'+str(column_number)
#         if (data[column_name] == person_id).sum() >= 1:
#             considered_features = [feature_name+str(column_number) for feature_name in person_features]
#             persons_dict[person_id][column_number] = data[data[column_name] == person_id][considered_features + ["Year"]]
#         column_number += 1

# len(persons_dict)

# persons_dict['36242'].keys()
# persons_dict['36242'][1]
# persons_dict['36242'][2]
# persons_dict['36242'][3]

In [12]:
# person_DF = pd.DataFrame(columns=person_features + ["Year"] + ["Rank"])

# new_df = pd.DataFrame(data=persons_dict['36242'][1].values, columns=person_features + ["Year"])
# new_df["Rank"] = 1
# person_DF = person_DF.append(new_df)

# new_df = pd.DataFrame(data=persons_dict['36242'][2].values, columns=person_features + ["Year"])
# new_df["Rank"] = 2
# person_DF = person_DF.append(new_df)
# person_DF

In [13]:
person_DF = pd.DataFrame(columns=person_features + ["Year"] + ["Rank"])

for person_id in person_unique_id:
    column_number = 1
    while(column_number <= 15):
        column_name = 'Person.ID.'+str(column_number)
        if (data[column_name] == person_id).sum() >= 1:
            considered_features = [feature_name+str(column_number) for feature_name in person_features]
            new_df = pd.DataFrame(data=data[data[column_name] == person_id][considered_features + ["Year"]].values, columns=person_features + ["Year"])
            new_df["Rank"] = column_number
            person_DF = person_DF.append(new_df)
            
        column_number += 1

person_features_numerical = [
    'Year.of.Birth.', 'Number.of.Successful.Grant.', 'Number.of.Unsuccessful.Grant.', 'A..', 'A.', 'B.', 'C.',
]

for person_feature_numerical in person_features_numerical:
    person_DF[person_feature_numerical] = person_DF[person_feature_numerical].astype(float)

person_DF.shape

(13035, 17)

In [14]:
person_DF.head(20)

,Person.ID.,Role.,Year.of.Birth.,Country.of.Birth.,Home.Language.,Dept.No..,Faculty.No..,With.PHD.,No..of.Years.in.Uni.at.Time.of.Grant.,Number.of.Successful.Grant.,Number.of.Unsuccessful.Grant.,A..,A.,B.,C.,Year,Rank
0,79062,CHIEF_INVESTIGATOR,1945,Australia,NaN,2813,25,NaN,>5 to 10,0,1,32,20,9,1,6,1.0
1,79062,CHIEF_INVESTIGATOR,1945,Australia,NaN,2813,25,NaN,>5 to 10,0,2,32,20,9,1,6,1.0
2,79062,CHIEF_INVESTIGATOR,1945,Australia,NaN,2813,25,NaN,>5 to 10,0,2,39,29,10,2,7,1.0
0,82432,CHIEF_INVESTIGATOR,1960,Australia,NaN,528,7,Yes,more than 15,0,2,0,0,0,0,7,2.0
1,82432,CHIEF_INVESTIGATOR,1960,Australia,NaN,528,7,Yes,more than 15,0,2,0,0,0,0,8,2.0
0,82432,CHIEF_INVESTIGATOR,1960,Australia,NaN,528,7,Yes,more than 15,0,2,0,1,4,0,7,4.0
0,1125477,CHIEF_INVESTIGATOR,1960,NaN,NaN,4153,64,NaN,>=0 to 5,0,2,0,0,0,0,8,1.0
1,1125477,CHIEF_INVESTIGATOR,1960,NaN,NaN,4153,64,NaN,>=0 to 5,0,2,0,0,0,0,8,1.0
0,15987,CHIEF_INVESTIGATOR,1960,Australia,NaN,1623,13,Yes,>5 to 10,0,0,1,3,2,2,5,3.0
1,15987,CHIEF_INVESTIGATOR,1960,Australia,NaN,1623,13,Yes,>5 to 10,0,0,1,3,2,2,5,3.0
0,58457,CHIEF_INVESTIGATOR,1965,Australia,NaN,653,7,NaN,Less than 0,0,1,0,0,0,0,6,1.0
0,314962,CHIEF_INVESTIGATOR,1975,Australia,NaN,2523,25,Yes,>=0 to 5,0,1,0,0,0,0,7,1.0
1,314962,CHIEF_INVESTIGATOR,1975,Australia,NaN,2523,25,Yes,>=0 to 5,0,1,0,0,3,1,8,1.0
0,65812,CHIEF_INVESTIGATOR,1945,Australia,English,2253,19,Yes,Less than 0,0,0,0,3,25,7,6,1.0
0,65812,CHIEF_INVESTIGATOR,1945,Australia,English,2253,19,Yes,Less than 0,0,2,0,0,0,0,7,2.0
1,65812,CHIEF_INVESTIGATOR,1945,Australia,English,2253,19,Yes,Less than 0,0,2,0,0,0,0,7,2.0
2,65812,CHIEF_INVESTIGATOR,1945,Australia,English,2253,19,Yes,>=0 to 5,0,2,0,0,0,0,8,2.0
3,65812,CHIEF_INVESTIGATOR,1945,Australia,English,2253,19,Yes,>=0 to 5,0,2,0,0,0,0,8,2.0
0,14187,CHIEF_INVESTIGATOR,1955,Australia,NaN,498,7,Yes,more than 15,1,0,1,4,0,0,7,1.0
0,14187,CHIEF_INVESTIGATOR,1955,Australia,NaN,498,7,Yes,more than 15,2,0,0,0,1,0,8,2.0

In [17]:
person_DF.dtypes

Person.ID.                                object
Role.                                     object
Year.of.Birth.                           float64
Country.of.Birth.                         object
Home.Language.                            object
Dept.No..                                 object
Faculty.No..                              object
With.PHD.                                 object
No..of.Years.in.Uni.at.Time.of.Grant.     object
Number.of.Successful.Grant.              float64
Number.of.Unsuccessful.Grant.            float64
A..                                      float64
A.                                       float64
B.                                       float64
C.                                       float64
Year                                      object
Rank                                     float64
dtype: object

In [19]:
len(person_DF[person_DF["No..of.Years.in.Uni.at.Time.of.Grant."].isnull()])

1734

In [20]:
person_DF[person_DF["Person.ID."] == "5812"]

,Person.ID.,Role.,Year.of.Birth.,Country.of.Birth.,Home.Language.,Dept.No..,Faculty.No..,With.PHD.,No..of.Years.in.Uni.at.Time.of.Grant.,Number.of.Successful.Grant.,Number.of.Unsuccessful.Grant.,A..,A.,B.,C.,Year,Rank
0,5812,CHIEF_INVESTIGATOR,1965.0,North America,English,2153,19,NaN,NaN,0.0,0.0,0.0,1.0,0.0,1.0,5,1.0
1,5812,CHIEF_INVESTIGATOR,1965.0,North America,English,2153,19,NaN,NaN,0.0,0.0,0.0,1.0,0.0,1.0,6,1.0
2,5812,CHIEF_INVESTIGATOR,1965.0,North America,English,2153,19,NaN,NaN,0.0,0.0,0.0,1.0,0.0,1.0,6,1.0
3,5812,CHIEF_INVESTIGATOR,1965.0,North America,English,2153,19,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0,7,1.0
4,5812,CHIEF_INVESTIGATOR,1965.0,North America,English,2153,19,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0,8,1.0
0,5812,CHIEF_INVESTIGATOR,1965.0,North America,English,2153,19,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,7,2.0

In [258]:
# person_DF.describe()

In [21]:
nb_rows = len(person_DF)
[(column_name, person_DF[column_name].isnull().sum() / nb_rows) for column_name in person_DF.columns]

[('Person.ID.', 0.0),
 ('Role.', 7.6716532412734941e-05),
 ('Year.of.Birth.', 0.00030686612965093976),
 ('Country.of.Birth.', 0.11591868047564251),
 ('Home.Language.', 0.90586881472957426),
 ('Dept.No..', 0.082086689681626385),
 ('Faculty.No..', 0.072036823935558117),
 ('With.PHD.', 0.38711162255466053),
 ('No..of.Years.in.Uni.at.Time.of.Grant.', 0.13302646720368239),
 ('Number.of.Successful.Grant.', 0.0),
 ('Number.of.Unsuccessful.Grant.', 0.0),
 ('A..', 0.0),
 ('A.', 0.0),
 ('B.', 0.0),
 ('C.', 0.00015343306482546988),
 ('Year', 0.0),
 ('Rank', 0.0)]

## Building contigency table by people

In [34]:
unique_roles, all_roles = process_column(data, "Role.")
unique_cob, all_cob = process_column(data, "Country.of.Birth.")
unique_homelanguage, all_homelanguage = process_column(data, "Home.Language.")
unique_nbyears, all_nbyears = process_column(data, "No..of.Years.in.Uni.at.Time.of.Grant.")

contigency_features = {
    "numeric": ["Year.of.Birth.", "Number.of.Successful.Grant.", "Number.of.Unsuccessful.Grant.", "A..", "A.", "B.", "C.", "Year", "Rank"],
    "categorical": [
        ("Role.", unique_roles), 
        ("Country.of.Birth.", unique_cob),
        ("Home.Language.", unique_homelanguage),
        ("No..of.Years.in.Uni.at.Time.of.Grant.", unique_nbyears)
    ]
}

contigency_df = pd.DataFrame(columns=contigency_features["numeric"] + [feature_name+str(unique_value) for feature_name, unique_values in contigency_features["categorical"] for unique_value in unique_values], dtype=float)
# for feature_name in contigency_features["numeric"]:
#     contigency_df[feature_name] = contigency_df[feature_name].astype(float)

contigency_df.dtypes

Year.of.Birth.                                       float64
Number.of.Successful.Grant.                          float64
Number.of.Unsuccessful.Grant.                        float64
A..                                                  float64
A.                                                   float64
B.                                                   float64
C.                                                   float64
Year                                                 float64
Rank                                                 float64
Role.EXT_CHIEF_INVESTIGATOR                          float64
Role.nan                                             float64
Role.STUD_CHIEF_INVESTIGATOR                         float64
Role.HONVISIT                                        float64
Role.STUDRES                                         float64
Role.DELEGATED_RESEARCHER                            float64
Role.PRINCIPAL_SUPERVISOR                            float64
Role.CHIEF_INVESTIGATOR                              float64
Role.EXTERNAL_ADVISOR                                float64
Country.of.Birth.nan                                 float64
Country.of.Birth.The Americas                        float64
Country.of.Birth.Middle East and Africa              float64
Country.of.Birth.Great Britain                       float64
Country.of.Birth.Asia Pacific                        float64
Country.of.Birth.New Zealand                         float64
Country.of.Birth.Australia                           float64
Country.of.Birth.South Africa                        float64
Country.of.Birth.Eastern Europe                      float64
Country.of.Birth.Western Europe                      float64
Country.of.Birth.North America                       float64
Home.Language.Other                                  float64
Home.Language.nan                                    float64
Home.Language.English                                float64
No..of.Years.in.Uni.at.Time.of.Grant.nan             float64
No..of.Years.in.Uni.at.Time.of.Grant.>5 to 10        float64
No..of.Years.in.Uni.at.Time.of.Grant.>10 to 15       float64
No..of.Years.in.Uni.at.Time.of.Grant.>=0 to 5        float64
No..of.Years.in.Uni.at.Time.of.Grant.Less than 0     float64
No..of.Years.in.Uni.at.Time.of.Grant.more than 15    float64
dtype: object

In [48]:
for person_ID in person_unique_id:
    person_applications = person_DF[person_DF["Person.ID."] == person_ID]
    person_applications

    new_values = []
    for feature_name in contigency_features["numeric"]:
        new_values.append(person_applications[feature_name].mean())

    nb_rows = len(person_applications)
    for feature_name, unique_values in contigency_features["categorical"]:
        for unique_value in unique_values:
            new_values.append( (person_applications[feature_name]==unique_value).sum() / nb_rows )

    contigency_df = contigency_df.append(pd.DataFrame(data=[new_values], columns=contigency_df.columns))

contigency_df

,Year.of.Birth.,Number.of.Successful.Grant.,Number.of.Unsuccessful.Grant.,A..,A.,B.,C.,Year,Rank,Role.EXT_CHIEF_INVESTIGATOR,...,Country.of.Birth.North America,Home.Language.Other,Home.Language.nan,Home.Language.English,No..of.Years.in.Uni.at.Time.of.Grant.nan,No..of.Years.in.Uni.at.Time.of.Grant.>5 to 10,No..of.Years.in.Uni.at.Time.of.Grant.>10 to 15,No..of.Years.in.Uni.at.Time.of.Grant.>=0 to 5,No..of.Years.in.Uni.at.Time.of.Grant.Less than 0,No..of.Years.in.Uni.at.Time.of.Grant.more than 15
0,1945.0,0.000000,1.666667,34.333333,23.000000,9.333333,1.333333,6.333333,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.0,0.0
0,1960.0,0.000000,2.000000,0.000000,0.333333,1.333333,0.000000,7.333333,2.666667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,1.0
0,1960.0,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1960.0,0.000000,0.000000,1.000000,3.000000,2.000000,2.000000,5.000000,3.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.0,0.0
0,1965.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1975.0,0.000000,1.000000,0.000000,0.000000,1.500000,0.500000,7.500000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1945.0,0.000000,1.600000,0.000000,0.600000,5.000000,1.400000,7.200000,1.800000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.000000,0.000000,0.400000,0.6,0.0
0,1955.0,1.333333,0.000000,0.666667,2.333333,0.333333,0.000000,7.000000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,1.0
0,1950.0,1.000000,0.666667,0.333333,1.000000,6.000000,0.666667,6.333333,2.333333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1960.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1945.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1980.0,0.875000,3.375000,0.000000,0.000000,0.000000,0.000000,7.250000,1.125000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1970.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1950.0,0.000000,0.000000,2.000000,2.000000,1.000000,1.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,0.0,0.0
0,1945.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1975.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,8.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1975.0,0.000000,1.000000,0.500000,0.000000,0.500000,0.000000,6.500000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.500000,0.000000,0.500000,0.0,0.0
0,1980.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1965.0,1.666667,0.333333,0.000000,1.333333,0.666667,0.000000,6.000000,1.666667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1955.0,2.571429,1.571429,0.000000,1.142857,0.142857,0.714286,6.571429,1.714286,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1970.0,0.333333,1.000000,5.000000,10.666667,0.333333,0.000000,6.666667,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.666667,0.000000,0.333333,0.0,0.0
0,1965.0,1.000000,0.000000,0.000000,2.000000,1.000000,1.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.0,0.0
0,1965.0,0.833333,5.083333,0.166667,5.666667,5.666667,0.750000,6.583333,1.250000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1965.0,1.100000,1.700000,1.300000,1.100000,1.500000,0.500000,7.000000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1975.0,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,5.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1975.0,1.000000,0.000000,4.000000,3.000000,0.000000,1.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1970.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,6.500000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1940.0,0.000000,1.000000,2.000000,7.000000,2.000000,1.000000,5.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1955.0,4.250000,0.125000,2.000000,5.125000,5.500000,1.750000,7.625000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1955.0,2.000000,4.250000,0.000000,0.875000,0.000000,3.500000,7.000000,1.312500,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,1975.0,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1955.0,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,6.500000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1960.0,0.000000,2.200000,0.000000,0.000000,0.400000,1.000000,7.000000,2.200000,0.0,...,0.0,0.0,0.0,1.0,0.0,0.600000,0.400000,0.000000,0.0,0.0
0,1960.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,6.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1960.0,0.000000,0.100000,8.800000,6.700000,2.300000,2.300000,6.100000,1.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.900000,0.100000,0.000000,0.0,0.0
0,1950.0,3.350000,4.700000,14.050000,14.300000,8.550000,5.900000,6.200000,2.200000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,1.0
0,1965.0,0.000000,2.000000,0.000000,5.000000,0.000000,0.000000,5.500000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1970.0,0.000000,1.500000,0.000000,1.000000,0.000000,0.000000,7.000000,1.000000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1975.0,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1965.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1970.0,0.600000,1.200000,0.200000,0.800000,0.000000,0.000000,6.600000,1.800000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1975.0,3.000000,0.000000,2.428571,6.000000,0.000000,3.000000,7.714286,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,NaN,0.500000,1.000000,5.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1970.0,0.000000,2.000000,1.000000,21.000000,1.000000,1.000000,6.500000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.0,0.0
0,1960.0,0.750000,0.750000,10.625000,3.875000,6.375000,0.875000,6.750000,2.875000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.500000,0.000000,0.0,0.5
0,1960.0,0.829268,15.024390,6.902439,16.536585,16.000000,3.707317,6.365854,1.487805,0.0,...,0.0,0.0,0.0,0.0,0.0,0.195122,0.000000,0.804878,0.0,0.0
0,1970.0,0.500000,0.000000,6.500000,6.000000,1.000000,0.000000,5.500000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1960.0,0.500000,0.750000,5.000000,1.500000,1.750000,0.500000,7.250000,1.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,0.0,0.0
0,1965.0,3.588235,3.882353,0.823529,0.000000,0.470588,0.117647,6.411765,1.176471,0.0,...,0.0,0.0,0.0,0.0,0.0,0.117647,0.000000,0.882353,0.0,0.0
0,1975.0,0.000000,2.500000,0.000000,0.500000,1.500000,0.500000,5.750000,1.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1950.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1970.0,1.000000,6.058824,1.235294,1.235294,0.000000,0.000000,6.352941,1.588235,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1965.0,0.000000,0.000000,0.000000,7.000000,2.000000,1.000000,5.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0
0,1980.0,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,8.000000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1950.0,1.000000,0.000000,0.500000,0.750000,0.500000,0.500000,6.000000,2.250000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,0.0,0.0
0,1955.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1975.0,0.500000,2.000000,6.750000,1.000000,2.000000,1.000000,7.250000,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,0.0
0,1970.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.500000,3.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1960.0,0.666667,0.333333,0.000000,2.666667,0.666667,0.000000,5.666667,1.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,0.0,0.0
0,1960.0,1.411765,4.000000,0.235294,0.823529,2.294118,1.352941,6.588235,1.058824,0.0,...,0.0,0.0,0.0,0.0,0.0,0.529412,0.470588,0.000000,0.0,0.0

In [50]:
# Building the contigency for person
data.head(1)

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,Faculty.No..15,With.PHD.15,No..of.Years.in.Uni.at.Time.of.Grant.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15,C.15,Year
0,1,1,NaN,NaN,A,8/11/05,280199,100.0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [68]:
def rfcd_codes(data, prefix, nb_max=5, length=1):
    unique_values = set([])
    for i in range(1, nb_max+1):
        unique_values.update([str(code)[:length] if not np.isreal(code) else np.nan for code in data[prefix+str(i)].unique()])
    return tuple(unique_values)

rcfd_codes_unique = rfcd_codes(data, "RFCD.Code.")
rcfd_codes_unique

(nan, '4', '2', '9', '0', '3')

In [116]:
def rfcd_codes(data, prefix, nb_max, length):
    unique_values = set([])
    for i in range(1, nb_max+1):
        unique_values.update([str(code)[:length] if not np.isreal(code) else np.nan for code in data[prefix+str(i)].unique()])
    return tuple(unique_values)

# rcfd_codes_unique = rfcd_codes(data, "RFCD.Code.")

# Build a dataframe with contingecy frequencies from a given spread column
def add_rfcd_aggregation(prefix1, prefix2, nb_max, unique_values, add_cardinal, suffix, length, keep_nan):
    nb_unique_values = len(unique_values)
    has_nans = np.nan in unique_values
    nan_index = unique_values.index(np.nan)
    new_feature_labels = [prefix2+str(value)+suffix for value in unique_values]
    if has_nans and not keep_nan:
        new_feature_labels.pop(nan_index)
    if add_cardinal:
        new_feature_labels.append("cardinal_"+prefix2)
    def nested_func(x):
        values_percentage = [0]*nb_unique_values
        cardinal = 0
        for i in range(1, nb_max+1):
            considered_value = x[prefix1+str(i)]
            current_value =  np.nan
            if not np.isreal(considered_value) and considered_value != '0':
                current_value = str(considered_value)[:length]
                cardinal += 1
            values_percentage[unique_values.index(current_value)] += x[prefix2+str(i)]/100.0
        if has_nans:
            values_percentage[nan_index] = 0
            if not keep_nan:
                values_percentage.pop(nan_index)
        if add_cardinal:
            values_percentage.append(cardinal)
        return pd.Series(values_percentage, index=new_feature_labels)
    return nested_func

# Build a dataframe with contingecy frequencies from a given spread column
def build_rfcd_aggregation(data, prefix1, prefix2, nb_max, length, add_cardinal=True, suffix="x", keep_nan=False):
    unique_values = rfcd_codes(data, prefix1, nb_max, length)
    return unique_values, data.apply(add_rfcd_aggregation(prefix1, prefix2, nb_max, unique_values, add_cardinal, suffix, length, keep_nan), axis=1, raw=True)

rcfd_codes_unique, rfcd_df = build_rfcd_aggregation(data, "RFCD.Code.", "RFCD.Percentage.", 5, 1, keep_nan=False)

In [117]:
rfcd_df

,RFCD.Percentage.4x,RFCD.Percentage.2x,RFCD.Percentage.9x,RFCD.Percentage.0x,RFCD.Percentage.3x,cardinal_RFCD.Percentage.
0,0.0,1.00,0.0,0.0,0.00,1.0
1,0.0,1.00,0.0,0.0,0.00,3.0
2,0.0,0.00,0.0,0.0,1.00,2.0
3,0.0,0.50,0.0,0.0,0.50,2.0
4,0.0,1.00,0.0,0.0,0.00,3.0
5,0.0,0.00,0.0,0.0,1.00,1.0
6,0.0,1.00,0.0,0.0,0.00,3.0
7,0.0,0.00,0.0,0.0,1.00,1.0
8,0.0,1.00,0.0,0.0,0.00,2.0
9,0.0,1.00,0.0,0.0,0.00,3.0
10,0.0,1.00,0.0,0.0,0.00,2.0
11,0.0,0.20,0.0,0.0,0.80,3.0
12,0.0,0.00,0.0,0.0,1.00,1.0
13,0.0,1.00,0.0,0.0,0.00,2.0
14,0.0,1.00,0.0,0.0,0.00,3.0
15,0.0,0.00,0.0,0.0,1.00,1.0
16,0.0,0.33,0.0,0.0,0.67,3.0
17,0.0,0.00,0.0,0.0,1.00,3.0
18,0.0,0.60,0.0,0.0,0.40,3.0
19,0.0,0.00,0.0,0.0,1.00,1.0
20,0.0,0.60,0.0,0.0,0.40,3.0
21,0.0,0.00,0.0,0.0,1.00,1.0
22,0.0,0.00,0.0,0.0,1.00,3.0
23,0.0,1.00,0.0,0.0,0.00,3.0
24,0.0,0.00,0.0,0.0,1.00,1.0
25,0.0,0.00,0.0,0.0,0.00,0.0
26,0.0,0.00,0.0,0.0,0.00,0.0
27,0.0,1.00,0.0,0.0,0.00,1.0
28,0.0,0.50,0.0,0.0,0.50,2.0
29,0.0,0.00,0.0,0.0,1.00,2.0
...,...,...,...,...,...,...
8678,0.0,0.00,0.0,0.0,1.00,1.0
8679,0.0,1.00,0.0,0.0,0.00,4.0
8680,0.0,1.00,0.0,0.0,0.00,1.0
8681,0.0,0.00,0.0,0.0,1.00,2.0
8682,0.0,0.00,0.0,0.0,1.00,1.0
8683,1.0,0.00,0.0,0.0,0.00,2.0
8684,0.0,1.00,0.0,0.0,0.00,2.0
8685,0.0,0.00,0.0,0.0,1.00,1.0
8686,0.0,0.00,0.0,0.0,1.00,1.0
8687,0.0,1.00,0.0,0.0,0.00,1.0
8688,0.0,1.00,0.0,0.0,0.00,3.0
8689,0.0,0.00,0.0,0.0,1.00,2.0
8690,0.0,0.00,0.0,0.0,1.00,2.0
8691,0.0,0.00,0.0,0.0,1.00,1.0
8692,0.0,0.60,0.0,0.0,0.40,2.0
8693,0.0,0.00,0.0,0.0,1.00,2.0
8694,0.2,0.00,0.0,0.0,0.80,3.0
8695,0.0,0.51,0.0,0.0,0.49,2.0
8696,0.0,1.00,0.0,0.0,0.00,1.0
8697,0.0,0.00,0.0,0.0,0.00,0.0
8698,0.0,0.00,0.0,0.0,1.00,1.0
8699,0.0,0.30,0.0,0.0,0.70,2.0
8700,0.0,1.00,0.0,0.0,0.00,3.0
8701,0.0,1.00,0.0,0.0,0.00,1.0
8702,0.0,0.00,0.0,0.0,0.00,0.0
8703,0.0,0.00,0.0,0.0,1.00,1.0
8704,0.0,0.00,0.0,0.0,1.00,2.0
8705,0.0,0.00,0.0,0.0,0.00,0.0
8706,0.0,1.00,0.0,0.0,0.00,3.0
8707,0.0,0.00,0.0,0.0,1.00,2.0

In [103]:
seo_codes_unique, seo_df = build_rfcd_aggregation(data, "SEO.Code.", "SEO.Percentage.", 5, 1)
seo_df

,SEO.Percentage.6x,SEO.Percentage.nanx,SEO.Percentage.9x,SEO.Percentage.0x,SEO.Percentage.7x,cardinal_SEO.Percentage.
0,0.0,0.0,0.0,0.0,1.0,1.0
1,0.0,0.0,0.0,0.0,1.0,2.0
2,0.0,0.0,0.0,0.0,1.0,2.0
3,0.0,0.0,0.0,0.0,1.0,2.0
4,0.0,0.0,0.0,0.0,1.0,1.0
5,0.0,0.0,0.0,0.0,1.0,1.0
6,0.0,0.0,0.0,0.0,1.0,2.0
7,0.0,0.0,0.0,0.0,1.0,1.0
8,0.0,0.0,0.0,0.0,1.0,1.0
9,0.0,0.0,0.0,0.0,1.0,2.0
10,0.0,0.0,0.0,0.0,1.0,1.0
11,0.0,0.0,0.0,0.0,1.0,3.0
12,0.0,0.0,0.0,0.0,1.0,1.0
13,0.0,0.0,0.0,0.0,1.0,1.0
14,0.0,0.0,0.0,0.0,1.0,2.0
15,0.0,0.0,0.0,0.0,1.0,1.0
16,0.0,0.0,0.0,0.0,1.0,3.0
17,0.0,0.0,0.0,0.0,1.0,3.0
18,0.0,0.0,0.0,0.0,1.0,1.0
19,0.0,0.0,0.0,0.0,1.0,1.0
20,0.0,0.0,0.0,0.0,1.0,3.0
21,0.0,0.0,0.0,0.0,1.0,1.0
22,0.0,0.0,0.0,0.0,1.0,1.0
23,1.0,0.0,0.0,0.0,0.0,3.0
24,0.0,0.0,0.0,0.0,1.0,1.0
25,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,1.0,2.0
28,0.0,0.0,0.0,0.0,1.0,1.0
29,0.0,0.0,0.0,0.0,1.0,2.0
...,...,...,...,...,...,...
8678,0.0,0.0,0.0,0.0,1.0,1.0
8679,0.0,0.0,0.0,0.0,1.0,2.0
8680,0.0,0.0,0.0,0.0,1.0,1.0
8681,0.0,0.0,0.0,0.0,1.0,2.0
8682,0.0,0.0,0.0,0.0,1.0,1.0
8683,0.0,0.0,0.0,0.0,1.0,2.0
8684,0.0,0.0,0.0,0.0,1.0,2.0
8685,0.0,0.0,0.0,0.0,1.0,1.0
8686,0.0,0.0,0.0,0.0,1.0,2.0
8687,0.0,0.0,0.0,0.0,1.0,1.0
8688,0.0,0.0,0.0,0.0,1.0,3.0
8689,0.0,0.0,0.0,0.0,1.0,1.0
8690,0.0,0.0,0.0,0.0,1.0,2.0
8691,0.0,0.0,0.0,0.0,1.0,1.0
8692,0.0,0.0,0.0,0.0,1.0,1.0
8693,0.0,0.0,0.0,0.0,1.0,2.0
8694,0.0,0.0,0.0,0.0,1.0,2.0
8695,0.0,0.0,0.0,0.0,1.0,1.0
8696,0.0,0.0,0.0,0.0,1.0,1.0
8697,0.0,0.0,0.0,0.0,0.0,0.0
8698,0.0,0.0,0.0,0.0,1.0,2.0
8699,0.0,0.0,0.0,0.0,1.0,2.0
8700,0.0,0.0,0.0,0.0,1.0,2.0
8701,0.0,0.0,0.0,0.0,1.0,2.0
8702,0.0,0.0,0.0,0.0,0.0,0.0
8703,0.0,0.0,0.0,0.0,1.0,1.0
8704,0.0,0.0,0.0,0.0,1.0,1.0
8705,0.0,0.0,0.0,0.0,0.0,0.0
8706,0.4,0.0,0.0,0.0,0.6,3.0
8707,0.0,0.0,0.0,0.0,1.0,2.0

In [74]:
rfcd_df

'a'

In [119]:
# build the list of all unique values of a given spread column, as a tuple
def process_column(data, prefix, nb_max):
    unique_values = set([])
    for i in range(1, nb_max+1):
        unique_values.update(data[prefix+str(i)].unique())
    return tuple(unique_values)

# Build a dataframe with contingecy frequencies from a given spread column
def add_contigency(prefix, nb_max, unique_values, add_cardinal, keep_nan):
    nb_unique_values = len(unique_values)
    has_nans = np.nan in unique_values
    nan_index = unique_values.index(np.nan)
    new_feature_labels = [prefix+str(value) for value in unique_values]
    if has_nans and not keep_nan:
        new_feature_labels.pop(nan_index)
    if add_cardinal:
        new_feature_labels.append("cardinal_"+prefix)
    def nested_func(x):
        values_frequency = [0]*nb_unique_values
        for i in range(1, nb_max+1):
            values_frequency[unique_values.index(x[prefix+str(i)])] += 1
        if has_nans:
            values_frequency[nan_index] = 0
            if not keep_nan:
                values_frequency.pop(nan_index)
        summe = sum(values_frequency)
        if summe != 0:
            values_frequency = [value/summe for value in values_frequency]
        if add_cardinal:
            values_frequency.append(summe)
        return pd.Series(values_frequency, index=new_feature_labels)
    return nested_func

# Build a dataframe with contingecy frequencies from a given spread column
def build_contigency(data, prefix, nb_max, add_cardinal=False, keep_nan=False):
    unique_values = process_column(data, prefix, nb_max)
    return unique_values, data.apply(add_contigency(prefix, nb_max, unique_values, add_cardinal, keep_nan), axis=1, raw=True)


unique_roles, role_contigency_df = build_contigency(data, "Role.", 15, add_cardinal=True)
role_contigency_df.head()

,Role.EXT_CHIEF_INVESTIGATOR,Role.STUD_CHIEF_INVESTIGATOR,Role.HONVISIT,Role.STUDRES,Role.DELEGATED_RESEARCHER,Role.PRINCIPAL_SUPERVISOR,Role.CHIEF_INVESTIGATOR,Role.EXTERNAL_ADVISOR,cardinal_Role.
0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1.0
1,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1.0
2,0.428571,0.000000,0.0,0.0,0.142857,0.000000,0.428571,0.0,7.0
3,0.500000,0.166667,0.0,0.0,0.000000,0.166667,0.166667,0.0,6.0
4,0.000000,0.000000,0.0,0.0,0.000000,0.000000,1.000000,0.0,1.0

In [120]:
# Build a dataframe with contingecy frequencies from a given spread column
def add_aggregation(prefixes, nb_max):
    feature_names_by_prefix = [[prefix+str(i) for i in range(1, nb_max+1)] for prefix in prefixes]
    methods_to_apply = [np.mean]
    new_feature_labels_by_prefix = [["mean_"+prefix] for prefix in prefixes]
    flat_new_labels = [new_feature_label for new_feature_labels in new_feature_labels_by_prefix for new_feature_label in new_feature_labels]
    def nested_func(x):
        values_by_prefix = [
            [x[feature_name] for feature_name in feature_names if np.isreal(x[feature_name]) and not np.isnan(x[feature_name])]
            for feature_names in feature_names_by_prefix
        ]
        aggregated_values_by_prefix = [[method(values) for method in methods_to_apply] if len(values) > 0 else [np.nan]*len(methods_to_apply) for values in values_by_prefix]
        return pd.Series(
            data=[aggregated_value for aggregated_values in aggregated_values_by_prefix for aggregated_value in aggregated_values], 
            index=flat_new_labels
        )
    return nested_func

# Build a dataframe with contingecy frequencies from a given spread column
def build_aggregation(data, prefix, nb_max):
    return data.apply(add_aggregation(prefix, nb_max), axis=1, raw=True)

aggregation_df = build_aggregation(data, ["Year.of.Birth."], 15)

In [123]:
aggregation_df.isnull().sum()

mean_Year.of.Birth.    470
dtype: int64

In [17]:
data["Sponsor.Code"] = data["Sponsor.Code"].fillna("MIA")
sponsor_indexes = data["Sponsor.Code"].value_counts().index

def reduce_sponsor(x):
    if x in sponsor_indexes[:5]:
        return x
    return "Other"
    
data["Sponsor.Code.Reduced"] = data["Sponsor.Code"].map(reduce_sponsor)

sponsor_reduced_dummies = pd.get_dummies(data["Sponsor.Code.Reduced"], prefix="Sponsor.Code.Reduced")
sponsor_reduced_dummies_features = list(sponsor_reduced_dummies.columns)
data.join(sponsor_reduced_dummies)

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,B.15,C.15,Year,Sponsor.Code.Reduced,Sponsor.Code.Reduced_21A,Sponsor.Code.Reduced_2B,Sponsor.Code.Reduced_34B,Sponsor.Code.Reduced_4D,Sponsor.Code.Reduced_MIA,Sponsor.Code.Reduced_Other
0,1,1,MIA,NaN,A,8/11/05,280199,100.0,0,0.0,...,NaN,NaN,5.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
1,2,1,2B,10A,B,11/11/05,280103,30.0,280106,30.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
2,3,1,29A,10B,A,14/11/05,321004,60.0,321216,40.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
3,4,1,40D,10B,C,15/11/05,270602,50.0,320602,50.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
4,5,0,59C,10A,A,16/11/05,260500,34.0,280000,33.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
5,6,1,4D,10A,NaN,19/11/05,321204,100.0,0,0.0,...,NaN,NaN,5.0,4D,0.0,0.0,0.0,1.0,0.0,0.0
6,7,0,2B,10A,NaN,19/11/05,270708,50.0,270203,30.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
7,8,0,28D,30B,A,19/11/05,321405,100.0,0,0.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8,9,1,2B,10A,H,19/11/05,260108,50.0,260109,50.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
9,10,1,2B,10A,NaN,19/11/05,270708,40.0,270704,30.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
10,11,1,2B,10A,G,19/11/05,230111,60.0,230112,40.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
11,12,0,136D,30B,NaN,19/11/05,270603,20.0,321003,30.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
12,13,1,4D,10A,NaN,19/11/05,320702,100.0,0,0.0,...,NaN,NaN,5.0,4D,0.0,0.0,0.0,1.0,0.0,0.0
13,14,0,MIA,NaN,NaN,19/11/05,291599,51.0,239901,49.0,...,NaN,NaN,5.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
14,15,1,2B,10A,NaN,19/11/05,280203,40.0,280106,30.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
15,16,0,100D,10B,NaN,19/11/05,321099,100.0,0,0.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
16,17,0,1A,10A,NaN,19/11/05,270603,33.0,321026,33.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
17,18,1,21A,50A,NaN,19/11/05,300903,33.0,370499,33.0,...,NaN,NaN,5.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
18,19,1,2B,10A,F,19/11/05,300508,40.0,270201,40.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
19,20,0,24D,30B,A,19/11/05,380103,100.0,0,0.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
20,21,1,148D,30B,A,19/11/05,270103,20.0,270106,40.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
21,22,0,12D,30B,NaN,19/11/05,370107,100.0,0,0.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
22,23,0,62B,10B,NaN,19/11/05,321021,40.0,321204,30.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
23,24,1,2B,10A,D,19/11/05,291801,60.0,291804,30.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
24,25,1,138B,30B,NaN,19/11/05,330305,100.0,0,0.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
25,26,0,MIA,NaN,A,19/11/05,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
26,27,0,MIA,NaN,C,19/11/05,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
27,28,0,MIA,NaN,NaN,19/11/05,270299,100.0,0,0.0,...,NaN,NaN,5.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
28,29,0,60D,30D,NaN,19/11/05,270603,50.0,321004,50.0,...,NaN,NaN,5.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
29,30,1,2B,10A,B,19/11/05,350201,60.0,380108,40.0,...,NaN,NaN,5.0,2B,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8678,8679,0,62B,10B,NaN,16/12/08,321021,100.0,0,0.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8679,8680,0,29A,10B,B,16/12/08,270102,10.0,270103,30.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8680,8681,1,24D,30B,A,17/12/08,270105,100.0,0,0.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8681,8682,0,90B,30D,NaN,17/12/08,321004,50.0,321003,50.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8682,8683,1,39C,30B,A,17/12/08,321012,100.0,0,0.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8683,8684,1,21A,50A,A,18/12/08,430101,80.0,430108,20.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8684,8685,1,21A,50A,A,18/12/08,280108,50.0,280212,50.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8685,8686,1,21A,50A,A,18/12/08,320704,100.0,0,0.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8686,8687,1,21A,50A,A,18/12/08,321014,100.0,0,0.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8687,8688,1,21A,50A,A,18/12/08,250302,100.0,0,0.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8688,8689,1,21A,50A,A,18/12/08,270106,40.0,270201,30.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8689,8690,1,21A,50A,A,18/12/08,321012,50.0,321004,50.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8690,8691,0,90B,30D,NaN,19/12/08,321004,50.0,321012,50.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8691,8692,0,24D,30B,A,19/12/08,320702,100.0,0,0.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8692,8693,0,MIA,NaN,NaN,19/12/08,270103,60.0,320799,40.0,...,NaN,NaN,8.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
8693,8694,0,90B,30D,NaN,19/12/08,321003,50.0,321004,50.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8694,8695,1,21A,50A,A,22/12/08,330103,50.0,330301,30.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8695,8696,1,MIA,NaN,A,22/12/08,270708,51.0,300802,49.0,...,NaN,NaN,8.0,MIA,0.0,0.0,0.0,0.0,1.0,0.0
8696,8697,1,34B,30C,A,22/12/08,270103,100.0,0,0.0,...,NaN,NaN,8.0,34B,0.0,0.0,1.0,0.0,0.0,0.0
8697,8698,0,329A,30D,C,23/12/08,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8698,8699,1,21A,50A,A,23/12/08,320202,100.0,0,0.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8699,8700,1,21A,50A,A,23/12/08,320202,70.0,270303,30.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8700,8701,1,21A,50A,A,23/12/08,270107,30.0,270304,50.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8701,8702,0,60D,30D,NaN,23/12/08,270303,100.0,0,0.0,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8702,8703,0,281A,10A,NaN,23/12/08,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8703,8704,1,21A,50A,A,23/12/08,321028,100.0,0,0.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8704,8705,1,21A,50A,A,23/12/08,340299,50.0,390114,50.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8705,8706,0,137A,30B,NaN,24/12/08,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,Other,0.0,0.0,0.0,0.0,0.0,1.0
8706,8707,1,21A,50A,A,24/12/08,280210,40.0,239901,40.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0
8707,8708,1,21A,50A,A,24/12/08,321012,70.0,321005,30.0,...,NaN,NaN,8.0,21A,1.0,0.0,0.0,0.0,0.0,0.0

In [15]:
data["Sponsor.Code.Reduced"]

0         MIA
1          2B
2       Other
3       Other
4       Other
5          4D
6          2B
7       Other
8          2B
9          2B
10         2B
11      Other
12         4D
13        MIA
14         2B
15      Other
16      Other
17        21A
18         2B
19      Other
20      Other
21      Other
22      Other
23         2B
24      Other
25        MIA
26        MIA
27        MIA
28      Other
29         2B
        ...
8678    Other
8679    Other
8680    Other
8681    Other
8682    Other
8683      21A
8684      21A
8685      21A
8686      21A
8687      21A
8688      21A
8689      21A
8690    Other
8691    Other
8692      MIA
8693    Other
8694      21A
8695      MIA
8696      34B
8697    Other
8698      21A
8699      21A
8700      21A
8701    Other
8702    Other
8703      21A
8704      21A
8705    Other
8706      21A
8707      21A
Name: Sponsor.Code.Reduced, dtype: object

In [18]:
np.max([1,2,3])

3

In [ ]:
# New feature for each person: Ratio of successfull grants

def add_ratio_successfull_grants():
    features_labels = [["Number.of.Successful.Grant." + str(index), "Number.of.Unsuccessful.Grant." + str(index)] for index in range(1, 16)]
    new_features_labels = ["Ratio.Successful.Grant."+str(index) for index in range(1,16)]
    def nested(x):
        values = [np.nan] * 15
        for index, (successful_feature, unsuccessful_feature) in enumerate(features_labels):
            if x[unsuccessful_feature] == 0:
                values[index] = 1.0 if x[successful_feature] > 0 else 0.0
            else:
                values[index] = x[successful_feature] / x[unsuccessful_feature]
        return pd.Series(values, index=new_features_labels)
    return nested
            

data = data.join(data.apply(add_ratio_successfull_grants(), axis=1, raw=True).head(20))

In [ ]:
# New feature for each person: Number of publications

def add_ratio_successfull_grants():
    features_labels = [["A.."+str(index), "A."+str(index), "B."+str(index), "C."+str(index)] for index in range(1, 16)]
    new_features_labels = ["Number.Publication."+str(index) for index in range(1,16)]
    def nested(x):
        values = [np.nan] * 15
        for index, (a_star, a_normal, b_normal, c_normal) in enumerate(features_labels):
            values[index] = 4*x[a_star] + 3*x[a_normal] + 2*x[b_normal] + x[c_normal]
        return pd.Series(values, index=new_features_labels)
    return nested
            

data = data.join(data.apply(add_ratio_successfull_grants(), axis=1, raw=True).head(20))

In [7]:
data.apply(lambda x: (x["Sponsor.Code"], x["Contract.Value.Band...see.note.A"]), axis=1).value_counts()

(4D, nan)      1177
(2B, nan)      1168
(21A, A )       841
(nan, nan)      325
(nan, A )       272
(4D, G )        207
(34B, A )       194
(4D, F )        158
(2B, D )        151
(4D, D )        126
(4D, E )        120
(2B, C )        108
(nan, B )       104
(2B, E )         92
(21A, nan)       85
(24D, B )        82
(32D, nan)       70
(nan, C )        66
(5A, A )         65
(2B, G )         63
(4D, A )         63
(4D, C )         57
(97A, A )        56
(40D, nan)       56
(6B, A )         55
(2B, B )         54
(4D, B )         51
(29A, A )        47
(2B, F )         46
(nan, D )        45
               ...
(241A, G )        1
(186B, nan)       1
(53A, C )         1
(137A, P )        1
(40D, D )         1
(278B, A )        1
(68D, nan)        1
(429A, nan)       1
(111C, E )        1
(297A, C )        1
(435C, nan)       1
(1A, D )          1
(257A, A )        1
(437A, B )        1
(85A, nan)        1
(177A, nan)       1
(270B, nan)       1
(266B, E )        1
(48D, H )         1
(308D, nan)       1
(357A, nan)       1
(274B, A )        1
(60D, G )         1
(342B, nan)       1
(87C, B )         1
(238B, A )        1
(183C, H )        1
(3C, C )          1
(191C, A )        1
(157A, A )        1
dtype: int64

In [8]:
data.apply(lambda x: (x["Grant.Category.Code"], x["Contract.Value.Band...see.note.A"]), axis=1).value_counts()

(10A, nan)    2369
(50A, A )      841
(30B, A )      603
(30B, nan)     368
(nan, nan)     325
(10A, D )      299
(10A, G )      297
(nan, A )      272
(30C, A )      257
(10A, E )      237
(10A, F )      225
(30B, B )      216
(10A, C )      190
(10B, A )      164
(20C, A )      134
(10A, A )      131
(10B, nan)     130
(20C, nan)     124
(10A, B )      121
(nan, B )      104
(50A, nan)      85
(nan, C )       66
(10B, C )       65
(10B, B )       64
(30D, nan)      56
(30C, nan)      50
(30B, C )       45
(30D, B )       45
(nan, D )       45
(10A, H )       39
              ...
(30C, E )        2
(40C, B )        2
(20A, I )        2
(30C, D )        2
(30E, A )        2
(20A, H )        2
(nan, O )        2
(30A, C )        2
(10B, H )        2
(30D, G )        2
(30G, G )        2
(nan, K )        2
(30G, C )        2
(20C, M )        1
(20A, J )        1
(20A, Q )        1
(nan, Q )        1
(10B, F )        1
(30E, C )        1
(30D, I )        1
(30F, B )        1
(20C, P )        1
(20C, K )        1
(20C, Q )        1
(10A, M )        1
(20C, I )        1
(30B, P )        1
(30A, A )        1
(10A, L )        1
(nan, L )        1
dtype: int64

In [22]:
data.apply(lambda x: (x["Sponsor.Code"], x["Grant.Category.Code"], x["Contract.Value.Band...see.note.A"]), axis=1).value_counts()

(2B, 10A, MIA)      1168
(4D, 10A, MIA)      1103
(21A, 50A, A )       841
(nan, nan, MIA)      325
(nan, nan, A )       272
(4D, 10A, G )        202
(34B, 30C, A )       194
(4D, 10A, F )        156
(2B, 10A, D )        151
(4D, 10A, D )        126
(4D, 10A, E )        116
(2B, 10A, C )        108
(nan, nan, B )       104
(2B, 10A, E )         92
(21A, 50A, MIA)       85
(24D, 30B, B )        82
(4D, 20C, MIA)        74
(32D, 30B, MIA)       70
(nan, nan, C )        66
(5A, 30B, A )         63
(2B, 10A, G )         63
(6B, 30B, A )         55
(4D, 10A, C )         55
(2B, 10A, B )         54
(97A, 30B, A )        53
(4D, 20C, A )         51
(29A, 10B, A )        47
(2B, 10A, F )         46
(40D, 10B, MIA)       46
(75C, 10B, A )        45
                    ...
(48D, 30D, D )         1
(274B, 30C, B )        1
(374B, 30B, A )        1
(179C, 20A, MIA)       1
(270B, 30D, MIA)       1
(26B, 10A, D )         1
(87C, 30C, F )         1
(179C, 20A, H )        1
(60D, 30D, G )         1
(60D, 30D, E )         1
(42B, 30B, A )         1
(47C, 10A, A )         1
(237A, 20A, MIA)       1
(300D, 30D, MIA)       1
(183C, 20C, D )        1
(357A, 30D, MIA)       1
(47C, 10A, MIA)        1
(38B, 30B, A )         1
(140D, 30B, MIA)       1
(105A, 10A, D )        1
(149A, 30B, E )        1
(342B, 20C, MIA)       1
(218B, 10A, A )        1
(202B, 30B, A )        1
(135C, 30D, MIA)       1
(94B, 10B, B )         1
(68D, 30B, MIA)        1
(252D, 20A, I )        1
(1A, 10A, H )          1
(370B, 30D, B )        1
dtype: int64

In [20]:
data['Contract.Value.Band...see.note.A'] = data['Contract.Value.Band...see.note.A'].fillna('MIA')

contract_value_band_values = {
    "A": [1, 50000],
    "B" : [50001, 100000],
    "C" : [100001, 200000],
    "D" : [200001, 300000],
    "E" : [300001, 400000],
    "F" : [400001, 500000],
    "G" : [500001, 1000000],
    "H" : [1000001, 2000000],
    "I" : [2000001, 3000000],
    "J" : [3000001, 4000000],
    "K" : [4000001, 5000000],
    "L" : [5000001, 6000000],
    "M" : [6000001, 7000000],
    "N" : [7000001, 8000000],
    "O" : [8000001, 9000000],
    "P" : [9000001, 10000000],
    "Q" : [10000001, 100000000]
}

for letter, values in contract_value_band_values.items():
    # The mean is divided by 100000.0 for avoiding de-normalization
    values.append(np.mean(values) / 100000.0)

def assign_value(x):
    if x["Contract.Value.Band...see.note.A"] is not 'MIA':
        return contract_value_band_values[x["Contract.Value.Band...see.note.A"].strip()][2]
    elif x["Sponsor.Code"] in ("2B", "4D"):
        return contract_value_band_values["A"][2]
    return np.nan

print(data.apply(assign_value, axis=1).isnull().sum())
type(data.apply(assign_value, axis=1))#.isnull()
# data["Contract.Value.Band.Values"] = data["Contract.Value.Band.Values"].fillna(np.nanmedian(data["Contract.Value.Band.Values"]))

1218

pandas.core.series.Series

In [16]:
("a", 2) == ("a", 2)

True

In [17]:
["a", 2] == ["a", 2]

True

In [21]:
data.apply(lambda x: (x["Sponsor.Code"], x["Grant.Category.Code"]), axis=1).value_counts()

(4D, 10A)      1845
(2B, 10A)      1741
(21A, 50A)      937
(nan, nan)      912
(34B, 30C)      228
(24D, 30B)      171
(4D, 20C)       161
(32D, 30B)      132
(5A, 30B)       104
(29A, 10B)       98
(40D, 10B)       95
(97A, 30B)       79
(6B, 30B)        71
(40D, 30B)       57
(149A, 30B)      56
(60D, 30D)       56
(75C, 10B)       53
(47C, 10B)       52
(62B, 10B)       49
(59C, 20C)       42
(7C, 10A)        41
(59C, 10A)       37
(89A, 30B)       37
(51C, 20C)       35
(77A, 30B)       31
(266B, 10A)      30
(36D, 10A)       30
(269A, 30B)      30
(188D, 30D)      28
(65A, 30B)       25
               ...
(196D, 10A)       1
(326B, 10B)       1
(145A, 30B)       1
(304D, 10A)       1
(134B, 10B)       1
(204D, 20C)       1
(428D, 30B)       1
(44D, 30G)        1
(258B, 30B)       1
(373A, 30D)       1
(362B, 30B)       1
(182B, 30B)       1
(299C, 30B)       1
(290B, 30D)       1
(432D, 10A)       1
(189A, 30D)       1
(311C, 30D)       1
(434B, 30B)       1
(294B, 30D)       1
(74B, 30C)        1
(65A, 30F)        1
(303C, 30C)       1
(259C, 30C)       1
(155C, 30B)       1
(156D, 30G)       1
(334B, 30B)       1
(437A, 30D)       1
(305A, 20A)       1
(159C, 30D)       1
(227C, 30E)       1
dtype: int64

In [24]:
data["Contract.Value.Band...see.note.A"].value_counts()

MIA    3563
A      2476
B       658
C       450
D       439
G       397
E       313
F       266
H        78
J        26
I        21
Q         7
K         6
P         2
L         2
O         2
M         2
Name: Contract.Value.Band...see.note.A, dtype: int64